### ISSUE TITLE
【建议】希望也转存下“推荐文章”tab

### ISSUE THREAD

**Issue by 0xuLiang** [slan-ning/coolshell-markdown#2]
coolshell 上有个推荐文章 tab，里面貌似是耗子（陈皓推荐的称呼，我也就暂且这样了）人工维护的精华文章列表，希望也转存下
https://coolshell.cn/featured

**Comment by slan-ning** [comment]
好的，有空弄下

**Comment by slan-ning** [comment]
已更新  https://github.com/slan-ning/coolshell-markdown/blob/main/featured.md
